// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Banco descartável usado pelo `migrate dev` e pelo
    // `migrate diff --from-migrations` para replicar as migrations e descobrir
    // o estado real que elas produzem. Sem isso o diff se recusa a rodar.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
